http://localhost:8080/control
### 
post http://localhost:8080/control/add
Content-Type: application/json

{
"name": "Medus",
"quantity_in_stock": 50,
"price": 6,
"foto_url": "https://nuotraukosprojektams.fra1.digitaloceanspaces.com/medus%20400g.jpg",
"quantity_kg": 0.3
}
###
DELETE http://localhost:8080/control/delete
Content-Type: application/json

{
"product_id":1
}
###
PATCH  http://localhost:8080/control/edit
Content-Type: application/json

{
"product_id":3,
"updatedInfoArr":[{"name":"quantity_in_stock", "value": 20}, {"name":"name", "value": "'Medutis'"}]
}
###
DELETE http://localhost:8080/control/orders
Content-Type: application/json

{
"id":1
}
###

POST http://localhost:8080/control/orders
Content-Type: application/json

{
"client_id": 1,
"amount": 20,
"product_id":2,
"product_name":"Medus",
"send_to":"adresas",
"email":"email"
}
###
GET http://localhost:8080/control/orders

