http://localhost:8080/products
### 
post http://localhost:8080/products/add
Content-Type: application/json

{
"name": "Medus",
"quantity_in_stock": 50,
"price": 6,
"foto_url": "https://nuotraukosprojektams.fra1.digitaloceanspaces.com/medus%20400g.jpg",
"quantity_kg": 3,
"description":"labai geras medus"
}
###
DELETE http://localhost:8080/products/delete
Content-Type: application/json

{
"product_id":7
}
###
PATCH  http://localhost:8080/products/edit
Content-Type: application/json

{
"product_id":3,
"updatedInfoArr":[{"name":"quantity_in_stock", "value": 20}, {"name":"name", "value": "'Medutis'"}]
}
###
DELETE http://localhost:8080/control/orders
Content-Type: application/json

{
"id":1
}
###

POST http://localhost:8080/control/orders
Content-Type: application/json

{
"juridinis":true,
  "amount":1,
  "amount_total_EUR":2,
  "product_id":"2",
  "product_name":"medus",
  "send_to":"namai",
  "email":"at@at.lt"
}
###
GET http://localhost:8080/control/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUzOTE0Njk0LCJleHAiOjE2NTM5MTgyOTR9.Fb08dTWdCYFSbusXtJSmRmiO2_U2Mqwy22vCEYeziQ0
###

POST http://localhost:8080/control/fiziniai
Content-Type: application/json

{
"name":"Pranas",
    "surname":"Masiotas",
   "adresas":"kaunas",
    "miestas":"kaunas",
    "el_pastas":"gai@kai.lt",
    "tel":56789234
}
###

POST http://localhost:8080/control/juridiniai
Content-Type: application/json

{
"imones_kodas":4567,
    "pvm_kodas":4567,
    "imones_pav":"kaunas",
   "adresas":"kaunas",
    "miestas":"kaunas",
    "el_pastas":"gai@kai.lt",
    "tel":56789234
}
###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username":"testas",
  "password":"testa"
}
###
POST https://jellyfish-app-xdnzk.ondigitalocean.app/login
Content-Type: application/json

{
  "username":"testas",
  "password":"testa"
}